name: Codacy Security Scan

on:
  push:
    branches: [ "feature" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "feature" ]


permissions:
  contents: read

jobs:
   codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - name: Install Codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
      - uses: actions/checkout@master
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ env.CODACY_PROJECT_TOKEN }}
          #coverage-reports: clover.xml
